---
fabric_name: ATD_MGMT

bgp_graceful_restart:
  enabled: true
  restart_time: 300

bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200


spine:
  defaults:
    platform: cEOS
    bgp_as: 65001
    loopback_ipv4_pool: 192.0.255.0/24
  nodes:
    - name: s1-spine1
      id: 1
      mgmt_ip: 192.168.0.10/24
    - name: s1-spine2
      id: 2
      mgmt_ip: 192.168.0.11/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.0.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.0.254.0/24
    uplink_interfaces: [Ethernet2, Ethernet3]
    uplink_switches:
      - s1-spine1
      - s1-spine2
    uplink_ipv4_pool: 172.30.255.0/24
    mlag_interfaces: [Ethernet1, Ethernet6]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384

  node_groups:
    - group: pod1
      bgp_as: 65101
      nodes:
        - name: s1-leaf1
          id: 11
          mgmt_ip: 192.168.0.12/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        - name: s1-leaf2
          id: 12
          mgmt_ip: 192.168.0.13/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
          raw_eos_cli: |
            router bgp 65101
              vrf bluevrf
                neighbor 1.2.3.1 remote-as 65501
            ip route vrf bluevrf 1.2.3.0/24 null0

    - group: pod2
      bgp_as: 65102
      nodes:
        - name: s1-leaf3
          id: 13
          mgmt_ip: 192.168.0.14/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        - name: s1-leaf4
          id: 14
          mgmt_ip: 192.168.0.15/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]

    - group: DC1_BORDER_LEAFS_GW
      bgp_as: 65103
      evpn_gateway:
        remote_peers:
          - hostname: s2-brdr1
          - hostname: s2-brdr2
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: s1-brdr1
          id: 15
          mgmt_ip: 192.168.0.100/24
          uplink_switch_interfaces:
            - Ethernet7
            - Ethernet7
        - name: s1-brdr2
          id: 16
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8

p2p_uplinks_mtu: 1500

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

name_servers:
  - 192.168.2.1
  - 8.8.8.8
  - 168.95.1.1

ntp:
  servers:
  - name: 10.70.32.146
    preferred: true
    vrf: default
    iburst: true
  - name: 10.70.32.147
    preferred: true
    vrf: default
    iburst: true

dns_domain: atd.lab
